import type { Metadata } from "next";
import { Rethink_Sans } from 'next/font/google'
 
const geist = Rethink_Sans({
  subsets: ['latin'],
})

import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={geist.className}>{children}
      </body>
    </html>
  );
}
